from enum import StrEnum


class MarketRegime(StrEnum):
    RISK_ON = "RISK_ON"
    NEUTRAL = "NEUTRAL"
    RISK_OFF = "RISK_OFF"
    INFLATION_SHOCK = "INFLATION_SHOCK"
    CRISIS = "CRISIS"


class PositionState(StrEnum):
    NEW = "NEW"
    HEALTHY = "HEALTHY"
    PROFIT_PROTECTION = "PROFIT_PROTECTION"
    PROFIT_AT_RISK = "PROFIT_AT_RISK"
    DRAWDOWN_WATCH = "DRAWDOWN_WATCH"
    THESIS_WEAKENING = "THESIS_WEAKENING"
    THESIS_BROKEN = "THESIS_BROKEN"
    RECOVERY_WATCH = "RECOVERY_WATCH"
    RECOVERY_CONFIRMED = "RECOVERY_CONFIRMED"
    EXIT_CANDIDATE = "EXIT_CANDIDATE"


class AssetSignal(StrEnum):
    STRONG_BUY = "STRONG_BUY"
    BUY = "BUY"
    HOLD = "HOLD"
    REDUCE = "REDUCE"
    EXIT = "EXIT"


class OrderStatus(StrEnum):
    PROPOSED = "PROPOSED"
    VALIDATED = "VALIDATED"
    APPROVED = "APPROVED"
    SUBMITTED = "SUBMITTED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    REJECTED = "REJECTED"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"
