from __future__ import annotations
from abc import ABC, abstractmethod
from collections.abc import Sequence
from portfolio_agent.broker.models import AccountSummary, BrokerPosition, OrderExecutionState, OrderIntent

class IbkrFacade(ABC):
    @abstractmethod
    def connect(self, host: str, port: int, client_id: int, timeout_seconds: int) -> None: ...
    @abstractmethod
    def disconnect(self) -> None: ...
    @abstractmethod
    def is_connected(self) -> bool: ...
    @abstractmethod
    def get_accounts(self) -> list[str]: ...
    @abstractmethod
    def get_account_summary(self, account_id: str) -> AccountSummary: ...
    @abstractmethod
    def get_positions(self, account_id: str) -> Sequence[BrokerPosition]: ...
    @abstractmethod
    def get_open_orders(self, account_id: str) -> Sequence[OrderExecutionState]: ...
    @abstractmethod
    def next_order_id(self) -> int: ...
    @abstractmethod
    def place_order(self, broker_order_id: int, intent: OrderIntent) -> OrderExecutionState: ...
    @abstractmethod
    def cancel_order(self, broker_order_id: int) -> None: ...
    @abstractmethod
    def get_order_state(self, broker_order_id: int) -> OrderExecutionState | None: ...
